on: 
  push:
    tags:
      - 'dressly@*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          source /home/runner/.bashrc 
          cd  dressly
          bun install

      - name: Build the app
        run: |
         source /home/runner/.bashrc 
          cd  dressly
          bun run build

      - name: Publish To Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "dressly" 
          directory: "dist"
          workingDirectory: "dressly"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Creating Artifact on CI
        uses: actions/upload-artifact@v4
        with:
            name: dressly
            path: dressly/dist
            retention-days: 1