on: 
  push:
    tags:
      - 'holadok@*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          source /home/runner/.bashrc 
          cd  holadok
          bun install

      - name: Build the app
        run: |
         source /home/runner/.bashrc 
          cd  holadok
          bun run build


      - name: Creating Artifact on CI
        uses: actions/upload-artifact@v4
        with:
            name: holadok
            path: holadok/build
            retention-days: 1
            
      - name: Publish To Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "holadok" 
          directory: "build"
          workingDirectory: "holadok"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
